drop table IF EXISTS caracterizacao_its.temp_avaliacao_ferramentas;

CREATE TABLE caracterizacao_its.temp_avaliacao_ferramentas(
    id_temp_avaliacao_ferramentas SERIAL,
	Grupo VARCHAR(32767),
	Linguagem VARCHAR(32767),
	"Código Participante" varchar(4),
	"Indicação de data e hora" VARCHAR(32767),
	"Horário início" VARCHAR(32767),
	"Nome da Função" VARCHAR(32767),
	"Descrição das atribuições" VARCHAR(32767),
	"Tipo de atividade" VARCHAR(32767),
	"Tempo de experiência" VARCHAR(32767),
	"Tipo local de trabalho" VARCHAR(32767),
	"Tamanho da equipe" VARCHAR(32767),
	"Frequência Registrar Requisição de Mudança em uma FGRM" VARCHAR(32767),
	"Frequência Decidir se uma Requisição de Mudança será aceita ou rejeitada e qual tipo de manutenção deverá ser aplicada" VARCHAR(32767),
	"Frequência Planejar a fila de Requisições de Mudança (RM) aceitas e atribuir atribuição das RM’s para o desenvolver mais apto." VARCHAR(32767),
	"Frequência Realizar as ações que irão solucionar a Requisição de Mudança" VARCHAR(32767),
	"Frequência Avaliar se uma Requisição de Mudança foi solucionada corretamente" VARCHAR(32767),
	"Frequência Definir os padrões e procedimentos que compõe o processo de manutenção que será utilizado" VARCHAR(32767),
	"Informe o nome da FGRM que você utiliza atualmente" VARCHAR(32767),
	"Relevância Apache Bloodhound" VARCHAR(32767),
	"Relevância Assembla Tickets" VARCHAR(32767),
	"Relevância Axosoft" VARCHAR(32767),
	"Relevância BMC Remedy Action Request System" VARCHAR(32767),
	"Relevância Bontq" VARCHAR(32767),
	"Relevância Brimir" VARCHAR(32767),
	"Relevância Bugzilla" VARCHAR(32767),
	"Relevância Debbugs" VARCHAR(32767),
	"Relevância FogBugz" VARCHAR(32767),
	"Relevância Fossil SCM" VARCHAR(32767),
	"Relevância FusionForge" VARCHAR(32767),
	"Relevância Gestionnaire libre de parc informatique" VARCHAR(32767),
	"Relevância GNATS GNU" VARCHAR(32767),
	"Relevância Google Code Hosting" VARCHAR(32767),
	"Relevância HP Quality Center" VARCHAR(32767),
	"Relevância IBM Rational ClearQuest" VARCHAR(32767),
	"Relevância IBM Rational Team Concert" VARCHAR(32767),
	"Relevância JIRA Software" VARCHAR(32767),
	"Relevância Kayako SupportSuite" VARCHAR(32767),
	"Relevância Launchpad" VARCHAR(32767),
	"Relevância Liberum Help Desk" VARCHAR(32767),
	"Relevância Mantis Bug Tracker" VARCHAR(32767),
	"Relevância Microsoft Dynamics CRM" VARCHAR(32767),
	"Relevância org-mode" VARCHAR(32767),
	"Relevância Open-source Ticket Request System" VARCHAR(32767),
	"Relevância Pivotal Tracker" VARCHAR(32767),
	"Relevância Plain Ticket" VARCHAR(32767),
	"Relevância Planbox" VARCHAR(32767),
	"Relevância QuickBase" VARCHAR(32767),
	"Relevância Redmine" VARCHAR(32767),
	"Relevância Request Tracker" VARCHAR(32767),
	"Relevância Roundup Issue Tracker" VARCHAR(32767),
	"Relevância StarTeam" VARCHAR(32767),
	"Relevância Supportworks" VARCHAR(32767),
	"Relevância SysAid" VARCHAR(32767),
	"Relevância Targetprocess" VARCHAR(32767),
	"Relevância Team Foundation Server" VARCHAR(32767),
	"Relevância Twproject" VARCHAR(32767),
	"Relevância TechExcel's DevTrack" VARCHAR(32767),
	"Relevância TestTrack" VARCHAR(32767),
	"Relevância The Bug Genie" VARCHAR(32767),
	"Relevância Trac Bug Tracking System" VARCHAR(32767),
	"Relevância TrackerSuite.Net" VARCHAR(32767),
	"Relevância Tuleap" VARCHAR(32767),
	"Relevância Usersnap Bug Tracking System" VARCHAR(32767),
	"Relevância Web Help Desk" VARCHAR(32767),
	"Relevância Wrike Project management software" VARCHAR(32767),
	"Relevância YouTrack" VARCHAR(32767),
	"Relevância Zoho BugTracker" VARCHAR(32767),
	"Relevância CA Service Desk" VARCHAR(32767),
	"Relevância SourceSafe" VARCHAR(32767),
	"Receber resultado" VARCHAR(32767),
	"Participar novamente" VARCHAR(32767),
	"Horário fim" VARCHAR(32767),
	"Informações adicionais" VARCHAR(32767)	
);


alter table caracterizacao_its.temp_avaliacao_ferramentas
add constraint pk_temp_avaliacao_ferramentas primary KEY(id_temp_avaliacao_ferramentas);

commit;
